### ISSUE TITLE
CPL的官方插件源版本同步问题

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-CPL#108]
如果可以提供最新版插件库的链接就好了，就像github的发布链接一样。

**Comment by linonetwo** [comment]
目前执行 

https://github.com/tiddly-gittly/TiddlyWiki-CPL/blob/bf06e1938053ee8f9662b0fcc6cba12842d9977d/package.json#L12 

这个命令就可以同步官方源，看谁有时间把它加到 Actions 里自动跑了
