### ISSUE TITLE
add plugin subsume

### ISSUE THREAD

**Issue by tomzcn** [tiddly-gittly/TiddlyWiki-CPL#115]
https://giffmex.org/gifts/subsume.html

以折叠的形式嵌入tiddler

**Comment by linonetwo** [comment]
看起来是不错，之前群里有人问过这个。

你加看看吧

**Comment by tomzcn** [comment]
> 



> 看起来是不错，之前群里有人问过这个。
> 
> 你加看看吧

看cpl文档说是在这里发issue就有人代劳加plugin。好吧。那我自己加加看。
