### ISSUE TITLE
What is CallbackInfo

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyWiki-CPL#122]
https://github.com/tiddly-gittly/TiddlyWiki-CPL/blob/master/tiddlers/CallbackInfo.tid

@Gk0Wk  这是什么呀？现在 TidGi 默认用 ipc 打开，而不用 http，这个会加载失败报错卡住，我就先注释掉了？

**Comment by linonetwo** [comment]
它想加载的内容长得像

```tw5
title: $:/temp/tw-cpl/plugin-callback-info
type: application/json

{"$:/plugins/twcloud/tiddlyweb-sse":"true|1.0.3","$:/plugins/Gk0Wk/CPL-Repo":"false|undefined"}
```

应该是构建后才有的，nodejs 模式时不需要

<img width="262" alt="截屏2023-07-04 20 22 45" src="https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/3746270/b1547e5b-e346-4cec-858c-027df0f881c3">

**Comment by Gk0Wk** [comment]
cpl网站用来拿cpl索引插件结果的。

**Comment by linonetwo** [comment]
为啥不打包进 HTML 里呢？因为太大了？

**Comment by Gk0Wk** [comment]
场景：在打开本地cpl项目进行编辑时
需求：能获取当前cpl最新的插件版本信息
获取该信息需要下载对应插件，因此在CI构建时生成该信息供本地使用

**Comment by linonetwo** [comment]
你去这个版本信息本地条目的是没有钱的，想要显示，只能靠云端信息，不过平时既然不会去填它，也就不会去改它和看他了，所以其实也无所谓。

还有问题是他在本地用太极打开的时候，会尝试从本地去加载，然后就失败了，所以我在本地用太极打开时候还是先不让它显示了

所以你说本地编辑的时候可以加载这信息也不大对呀，因为它是用相对路径尝试从本地去加载，不会从云端去加载呀

**Comment by Gk0Wk** [comment]
我也忘了。要不直接删掉吧
