### ISSUE TITLE
cpl字段更新问题

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TiddlyWiki-CPL#130]
通过命令行批量导入插件后, 如果插件移除了parent-plugins字段, cpl.xxx 相关的字段不会自动更新, 需要手动更新

![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/72405338/5c3cf00b-4cf9-4840-aaca-d2a2d52b038b)

**Comment by linonetwo** [comment]
不大懂这是咋搞的，你来改改吧

**Comment by Gk0Wk** [comment]
在这里

https://github.com/tiddly-gittly/TiddlyWiki-CPL/blob/master/scripts/build/merge.ts

**Comment by Gk0Wk** [comment]
所以问题解决了没 @oeyoews
