### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyWiki-CPL#134]
https://github.com/tiddly-gittly/TiddlyWiki-CPL/actions/runs/6256101601/job/16986447386

@Gk0Wk 这个是哪里把东西放内存里了吗，内存爆了

**Comment by linonetwo** [comment]
没看出是哪里有存内存里，难道是 $tw.wiki 里？

**Comment by Gk0Wk** [comment]
代码中没有内存逃逸，每个library导入后，相关内存应该都释放了

**Comment by linonetwo** [comment]
好像上次修好了
