### ISSUE TITLE
CPL 不可用的情况

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyWiki-CPL#135]
目前 https://tiddly-gittly.github.io/TiddlyWiki-CPL/library/index.html  404 了，可能是构建的问题，因为 https://tiddly-gittly.github.io/TiddlyWiki-CPL/#Index:Index 还在

netlify 那个经常有问题不知为啥

**Comment by Gk0Wk** [comment]
这也太顶了吧，可是我本地跑是没问题的，文件都在

**Comment by linonetwo** [comment]
你本地怎么跑的，我想试试，但是它每次要下载一大堆东西就很慢

**Comment by Gk0Wk** [comment]
scripts/build/library.ts 的 126 行加个 break; 只下载一个插件

**Comment by linonetwo** [comment]
我之后再看看吧，这边其实可以根据 node env ，进入 debug 模式，自动这样

**Comment by linonetwo** [comment]
试了一下，本地的确有 index.html ，不知为啥构建后没了

**Comment by linonetwo** [comment]
> github page没有部署在分支上吗，直接解压artifact吗

这你不是之前问过好几次了嘛，现在都是 Action 部署了，你看看那个 Action 就知道了

**Comment by linonetwo** [comment]
奇怪了 https://github.com/tiddly-gittly/TiddlyWiki-CPL/actions/runs/6260577129/job/16998884761

这文件在线上就是没了。

如果在字节，操作就是立即回滚版本，然后慢慢排查，在测试环境多试试，下周一再上线试试，反正这样把线上搞挂了不大好

**Comment by linonetwo** [comment]
可能是这里没成功

https://github.com/tiddly-gittly/TiddlyWiki-CPL/blob/91fde3a83491893f271ca0ddf6e70a2597e31097/scripts/build/library.ts#L257-L271

**Comment by Gk0Wk** [comment]
callback是这样的，最新版本和是否需要重启的信息，只有ci才能拿到，这个tid用来给本地wiki打开的时候看


如果build之后立刻ls，能看到html吗

**Comment by linonetwo** [comment]
发现这个log之后就中断了，结果发现是return了
