### ISSUE TITLE
能做一个插件版本归档吗？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TiddlyWiki-CPL#140]
![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/109711900/efdd890f-6266-4fd9-a809-d07004c3193e)

https://bramchen.github.io/tw5-docs/zh-Hans/#TiddlyWiki%20Archive

类似这样的。虽然可能没啥作用，但可能有些人需要。不过这个应该算是插件作者做的事情吧。算了，先不管了。

**Comment by dongrentianyu** [comment]
只是一个想法。

**Comment by Gk0Wk** [comment]
已经做了

**Comment by linonetwo** [comment]
所以插件作者最好把基本的文档也包含进插件去，不然旧版文档肯定是没了，因为文档我们不会帮忙归档

**Comment by Gk0Wk** [comment]
在 [#154] 继续讨论
