### ISSUE TITLE
Auto Import 3rd Party Plugin Libraries not working

### ISSUE THREAD

**Issue by oflg** [tiddly-gittly/TiddlyWiki-CPL#145]
When I update librarys.json or run action, this feature does not work

**Comment by oflg** [comment]
[sortan[]](https://github.com/tiddly-gittly/TiddlyWiki-CPL/actions/runs/6478697032/job/17590896172)

**Comment by linonetwo** [comment]
我之前应该已经修好了吧

**Comment by linonetwo** [comment]
看错了，没好

**Comment by linonetwo** [comment]
现在好了 https://github.com/tiddly-gittly/TiddlyWiki-CPL/actions/runs/6505997753/job/17670681247

**Comment by linonetwo** [comment]
又看错了，我老把 build-and-deploy 看成这个的

**Comment by linonetwo** [comment]
![截屏2023-10-13 19 35 37](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/3746270/47b4ffeb-ea08-46c7-86e3-a2067faee093)

https://github.com/tiddly-gittly/TiddlyWiki-CPL/actions/workflows/update-library.yml

现在好了

**Comment by linonetwo** [comment]
这个是 @oeyoews 的插件源，@oeyoews 记得更新一下

**Comment by linonetwo** [comment]
这个更新完后，还要等另一个 Action 再更新，网站才会出现

**Comment by oflg** [comment]
> 等另一个 Action 再更新，网站才会出现

等到现在还没出现🤣

**Comment by linonetwo** [comment]
你看 tiddlers 文件夹里有吗，这个应该是有在正常运行的

<img width="1060" alt="截屏2023-10-14 11 49 38" src="https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/3746270/441d46a8-7317-4c11-bd05-585acff543b5">

**Comment by oflg** [comment]
>  tiddlers 文件夹里有吗

没有

**Comment by oeyoews** [comment]
cpl 果然多了一批插件， 刚写的 vue-gemini 都加上了， 再也不用手动导入了。

cpl 下一步是不是可以加个下架插件的功能， 我cpl的插件查了一下， 都将近200个了， 其实有一半都改名或者归档了， cpl 通过library 导入的插件其实并没有被缓存， 只有上传插件的源文件才可以
