### ISSUE TITLE
窗口弹出问题

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TiddlyWiki-CPL#147]
不再弹出的配置应该放在浏览器里面

**Comment by linonetwo** [comment]
<img width="1701" alt="截屏2023-10-12 16 21 51" src="https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/3746270/d46e5458-07c7-4bf5-8e49-23778f6f589e">

我的博客上也会弹窗了，不大好 @Gk0Wk https://wiki.onetwo.ren/#:Index

**Comment by Gk0Wk** [comment]
下面有不再弹出啊

**Comment by linonetwo** [comment]
> 下面有不再弹出啊

之前没看到，其实应该搞成一个底部按钮「关闭并不再弹出」比较好

**Comment by linonetwo** [comment]
> 不再弹出的配置应该放在浏览器里面

不行，放浏览器里的话，博客那边怎么知道勾选过呢？所以得像现在这样用条目才行

<img width="988" alt="截屏2023-10-13 12 56 37" src="https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/3746270/05f22762-75f0-4c8a-8aa2-532be29306a0">

**Comment by Gk0Wk** [comment]
我会把不再弹出放在最上面
