### ISSUE TITLE
Tidme 安装失败

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyWiki-CPL#151]
<img width="1029" alt="截屏2023-10-13 16 24 32" src="https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/3746270/ea73bf4f-0bc4-43a1-83e8-ac86928f4f51">

https://tw-cpl.netlify.app/repo/tiddlywiki_confetti/__meta__.json 404

别的像 https://tw-cpl.netlify.app/repo/tidme_fsrs4tw/__meta__.json 是 200

@oflg 是不是依赖不在cpl上？

**Comment by linonetwo** [comment]
是官方插件可能没导入进去

**Comment by oflg** [comment]
这个插件在TW的https://github.com/Jermolene/TiddlyWiki5/tree/confetti-plugin分支，还没有合并到主分支发布，所以安装不上。只能手动拖放。

**Comment by linonetwo** [comment]
好吧，要不要先手动加进来一下

**Comment by oflg** [comment]
已添加 https://github.com/tiddly-gittly/TiddlyWiki-CPL/commit/3acaca50c4381271ef59b83e1f57cfc442f61d29

**Comment by linonetwo** [comment]
还得加上对应的插件描述吧，我加一个

**Comment by Gk0Wk** [comment]
解决了吗，看一下cache里面对应位置有没有

**Comment by oflg** [comment]
解决了
