### ISSUE TITLE
缺失 https://tw-cpl.netlify.app/repo/TWaddle_ListTree/__meta__.json

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyWiki-CPL#152]
在安装 Aggregation-people 的时候

这个 TWaddle_ListTree 是啥，从没听过

**Comment by linonetwo** [comment]
xp 里有，不过还是找到了原始出处装了 f112df3

**Comment by Gk0Wk** [comment]
为什么能搜到但是meta没有啊，按理来说要没有都没有

**Comment by Gk0Wk** [comment]
是不是因为原插件有但是以来插件没有

**Comment by linonetwo** [comment]
你的插件依赖了，就顺便添加一下嘛

**Comment by Gk0Wk** [comment]
> ![img](https://i.imgur.com/iXtdtRu.png)
> 
> 
> 
> * 如果依赖缺失, 可以跳过依赖, 提示用户(cpl现在还没有上传cdr/markdown-more插件, 所以造成安装失败)

今天改一下

**Comment by Gk0Wk** [comment]
原本的tw没有soft-dependents，我们可以加一下

**Comment by linonetwo** [comment]
应该是 optionalDependency ，参考 npm 的

**Comment by Gk0Wk** [comment]
可以，但是这就超出原来的tw太多了

**Comment by linonetwo** [comment]
这就不太方便了，难道要用户的笔记网页上放两个同样的插件文件吗？这个空间占用成两倍了。
