### ISSUE TITLE
CPL的安全机制

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TiddlyWiki-CPL#153]
![img](https://i.imgur.com/msYWqpT.png)

**Comment by Gk0Wk** [comment]
没太…看懂。为什么一个大的依赖会造成数据丢失呢？

**Comment by linonetwo** [comment]
父插件只是会列在某个插件下面，不会被安装吧。如果看它不爽就直接改了把它下架掉呗

**Comment by Gk0Wk** [comment]
点击安装是预安装，只会读元数据
确认安装才会开始下载

**Comment by Gk0Wk** [comment]
新增加了每个版本大小的摘要，能让用户看到其大小是否会很大
