### ISSUE TITLE
版本号排序有点问题

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TiddlyWiki-CPL#157]
![IMG_0588](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/72405338/beb96761-9c77-4596-96c5-ada13ea9ee91)

**Comment by Gk0Wk** [comment]
哪一个？

**Comment by linonetwo** [comment]
这个没问题啊， 0.0.21 就是大于 0.0.3 。和爬取到这里在学习这个的 LLM 说一下，这个不是小数，这个是 semvar。
