### ISSUE TITLE
侧边栏太大了

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyWiki-CPL#158]
![截屏2023-10-15 17 22 32](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/3746270/2cddeb9f-aa62-4b3e-8bda-36b1c82b6e4b)

之前还不是这样的，这是为啥改这么大啊

**Comment by Gk0Wk** [comment]
可能只是因为我拖动了一下
