### ISSUE TITLE
关于插件格式，是 json 还是 tiddlers

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyWiki-CPL#166]
https://github.com/Jermolene/TiddlyWiki5/issues/7741

json 需要附带 meta 文件

而 tiddlers 就是单个 json 文件，包含多个 tiddlers 在里面。

**Comment by oeyoews** [comment]
如果希望json被拖进的时候不产生meta文件, 最简单的方法就是再 plugin.fin 加上一个 xxx#xx 的不标准字段, 这也就是为什么moderndev 打出来的插件, 不会产生meta文件的原因, 这也是之前为什么有的时候为什么产生的是json条目, 而不是tid/md条目的原因, https://github.com/Jermolene/TiddlyWiki5/issues/7799 相关机制应该都在filesystem.js 文件里面

**Comment by oeyoews** [comment]
我在打包书籍插件的时候 加上了 `book#author`, https://oeyoews.github.io/reading-books-with-tiddlywiki/#%24%3A%2Fplugins%2Fbooks%2F%E5%8A%AB%E6%8C%81 可以用这个文件测试一下

**Comment by linonetwo** [comment]
> 加上一个 xxx#xx 的不标准字段

原来是这样，反正既然这样了就得保持住了，不然升级插件的时候就会出问题了。

**Comment by Gk0Wk** [comment]
> 最简单的方法就是再 plugin.fin 加上一个 xxx#xx 的不标准字段, 这也就是为什么moderndev 打包出来的插件, 不会产生meta文件的原因

我都不知道，居然歪打正着
