### ISSUE TITLE
bug：插件依赖检测不正常 😭从controlPanel->插件->太微中文社区插件源(大陆加速版)访问  空白

### ISSUE THREAD

**Issue by king0billy** [tiddly-gittly/TiddlyWiki-CPL#169]
从controlPanel->插件->太微中文社区插件源(大陆加速版)访问  空白，但从controlPanel->CPL正常
![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/52921954/af4a3aeb-f9f6-4854-9d95-488c527eb721)

**Comment by king0billy** [comment]
![bf958366-23fc-4a02-8241-4b9cffe6aee1](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/52921954/314ca3b8-5138-4776-86a9-1408f9a87871)
而且cpl的依赖检测有问题

**Comment by Gk0Wk** [comment]
修好了应该
