### ISSUE TITLE
CPL更新只更新meta文件版本，没有实质性的插件内容更新。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-CPL#174]
![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/32425955/9b27a6f0-d02e-4de5-9f0e-c3d20a15090d)

**Comment by oeyoews** [comment]
可能这个插件只是升级了版本号，kookma的插件本身其实并没有任何改动

**Comment by Zacharia2** [comment]
欧克克
