### ISSUE TITLE
vuewiki plugin

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TiddlyWiki-CPL#184]
搜了下 tiddlywiki vue， 还真的有人写了这个类似的插件

https://github.com/Guitlle/vuewiki?tab=readme-ov-file

**Comment by linonetwo** [comment]
你这么说我就翻了一下，他还写了个追踪习惯的，我现在也在写，他从来都不宣传，大家都不知道啊

**Comment by oeyoews** [comment]
github 提交记录都是六年前了，可能他不用tiddlywiki 了吧。 当时应该还没有论坛， 所以只能在 google group 看到

<img width="1094" alt="image" src="https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/72405338/bd19f1c1-0649-4a3f-9918-35a8e0b83a63">
