### ISSUE TITLE
用 vue 重新搓了一个cpl 的插件搜索

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TiddlyWiki-CPL#187]
<img width="853" alt="image" src="https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/72405338/0f9dbea0-6a3d-4b20-9d10-41a7a6446f36">

wikitext 后期维护确实不太方便。

**Comment by linonetwo** [comment]
之后可以用 svelte 这样的无运行时开发框架，更容易被大家接受。

所见即所得和白板，大家是没办法才不得不装react的，如果有可选择的话，用户说不定都不愿意装react运行时。

**Comment by oeyoews** [comment]
https://talk.tiddlywiki.org/t/support-for-svelte-plugin-in-modern-tiddlydev-make-complex-js-plugin-smaller/10621 之前还以为可以不用构建工具写svelte， 不用运行时的话看来都少不了构建工具这一步

**Comment by linonetwo** [comment]
但是之后就不需要额外插件了
