### ISSUE TITLE
Filter Error: Unknown prefix for filter run

### ISSUE THREAD

**Issue by realaaa** [tiddly-gittly/TiddlyWiki-CPL#199]
hi guys! 

installed it as per hint from https://tiddly-gittly.github.io/tw-echarts/#How%20do%20I%20install%20this%20plugin%3F

looks like it installed OK - but now it cannot list the list of plugins with this error, what could be the issue? 

![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/10916555/762838cc-5037-4321-b539-2f05e493af32)

I am running it in a container as node.js on Synology and accessing over local network (if this provides any more hints). Version is 5.1.23

Thanks!

**Comment by realaaa** [comment]
thanks ! I'll try that eventually yep, do we know what is the supported version though?

**Comment by linonetwo** [comment]
Always use latest official version.

**Comment by linonetwo** [comment]
use TiddlyWIki 5.3.6
