### ISSUE TITLE
正反链展示插件 TOC-Generic 不错，可以添加

### ISSUE THREAD

**Issue by oflg** [tiddly-gittly/TiddlyWiki-CPL#20]
https://hchaase.github.io/HC-Plugins/#TOC-Generic%20Introduction

**Comment by Gk0Wk** [comment]
已添加，现在CPL项目可以使用`npm run importplugin`一键导入插件

<img width="658" alt="image" src="https://user-images.githubusercontent.com/16955102/159332926-edd86dfa-e60d-42f3-a3ff-9165716886a3.png">
