### ISSUE TITLE
Plugin Source Bug

### ISSUE THREAD

**Issue by GoogolOwO** [tiddly-gittly/TiddlyWiki-CPL#209]
I trying use the Chinese Plugin Source (not for CPL), it can't be load. I trying to open the Console, I looked a error:

```
Uncaught SyntaxError: Invalid or unexpected token (at index.html:12:405612)
```

Plugin Source: [太微中文社区插件源(大陆加速版)](https://note-wiki.tiddlyhost.com/#%24%3A%2Fconfig%2FTiddlyWiki-CPL%2FNetlify)

I want to let solve it.

**Comment by linonetwo** [comment]
你可能是旧版发行版的受害者，新版 https://tiddly-gittly.github.io/Tiddlywiki-NodeJS-Github-Template 已经不带这几个过时的插件源了，都用 CPL

**Comment by linonetwo** [comment]
先关闭了，因为现在只支持 CPL，只推荐 CPL。

**Comment by GoogolOwO** [comment]
谢谢
________________________________
发件人: lin onetwo ***@***.***>
发送时间: 2024年7月1日 18:38
收件人: tiddly-gittly/TiddlyWiki-CPL ***@***.***>
抄送: Googol ***@***.***>; Author ***@***.***>
主题: Re: [tiddly-gittly/TiddlyWiki-CPL] Plugin Source Bug (Issue #209)


先关闭了，因为现在只支持 CPL，只推荐 CPL。

―
