### ISSUE TITLE
[IDEA] Prevent Update Message for Plugins Require Newer TiddlyWiki

### ISSUE THREAD

**Issue by kookma** [tiddly-gittly/TiddlyWiki-CPL#211]
* Each plugin declares the required TW core version
* TiddlyWIki-plugins shows a message if it finds a newer plugin installed on the Wiki
* Add this feature to not allow updating. not display the update message if the core version required by a plugin is higher than the host TiddlyWiki.

Reason: I am updating some kookma plugins like Shiraz, Utility, Favorites which require TW 5.3.3 above. Also some are NOT back compatible.

**Comment by linonetwo** [comment]
I think you means CPL. I think this is not difficult to add, but I'm working on other stuff, and I personally don't need this because TidGi app is always in latest tw version.

**Comment by kookma** [comment]
Yes, I mean CPL. No rush, add it when you find spare time.
Thank you

**Comment by linonetwo** [comment]
I think we already have this feature

https://github.com/tiddly-gittly/TiddlyWiki-CPL/blob/20ab462b21cfdba0c24994a839dde93d77bab3eb/tiddlers/CPLPlugin/core.js#L107
