### ISSUE TITLE
登记插件 stroll

### ISSUE THREAD

**Issue by blackwint3r** [tiddly-gittly/TiddlyWiki-CPL#214]
https://giffmex.org/stroll/stroll.html
非常好用的插件，尤其是双栏模式和显示不同样式的反向链接。 发现CPL中没有，希望能登记。

**Comment by linonetwo** [comment]
这个好像不是插件，而是混在wiki里的一堆笔记组成的功能，这是比较过时的做法了，不是插件就没法通过插件源分发的。

**Comment by linonetwo** [comment]
像太记这样的现代发行版，所有功能都是插件，没有任何预置的纯笔记，所以一切都能用 CPL 来一键升级。但 stroll 没做到，有时候国外的太微老用户有点转不过弯来。
