### ISSUE TITLE
Undefined widget 'let'

### ISSUE THREAD

**Issue by yoghurtlee-thu** [tiddly-gittly/TiddlyWiki-CPL#220]
如题。在使用 Timimi 时，安装 CPL 后出现问题：

<img width="1466" alt="image" src="https://github.com/user-attachments/assets/268877fa-a140-4433-8a5f-ac1e243b6fd0">

TiddlyWiki 新手，对这方面的知识不是很了解，希望大佬能出手相助。

此致。

**Comment by oeyoews** [comment]
https://talk.tiddlywiki.org/t/tw5-undefined-widget-let/5391  大概率是你tiddlywiki版本太低了， 看看怎么升级下版本

**Comment by yoghurtlee-thu** [comment]
问题已解决，简单讲一下方法，供后来者参考。

使用 TiddlyWiki 官方的升级工具 <https://tiddlywiki.com/upgrade.html> 即可。

再次感谢 CPL 和 TiddlyWiki 的开发者们，祝万事胜意。
