### ISSUE TITLE
Add Streams to CPL

### ISSUE THREAD

**Issue by saqimtiaz** [tiddly-gittly/TiddlyWiki-CPL#36]
I have had a user request that the Streams plugin be made available via the CPL.

https://saqimtiaz.github.io/streams/#%24%3A%2Fplugins%2Fsq%2Fstreams
or https://saqimtiaz.github.io/SQPL/library/recipes/library/tiddlers/%2524%253A%252Fplugins%252Fsq%252Fstreams.json

It might also be nice to add the FileUploads plugins:
https://github.com/saqimtiaz/SQPL/tree/gh-pages/library/recipes/library/tiddlers

**Comment by Gk0Wk** [comment]
Add plugins in your library🎉
