### ISSUE TITLE
新的布景主题：Notebook

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-CPL#56]
GitHub主页：https://github.com/NicolasPetton/Notebook

主题主页：https://nicolas.petton.fr/tw/notebook.html

适配移动与PC端。
下载链接：
![image](https://user-images.githubusercontent.com/32425955/179187152-a8ccef2a-558d-40cd-8c57-5ff07df65266.png)

主题展示
![image](https://user-images.githubusercontent.com/32425955/179187070-19604263-80cd-40aa-9ffc-1099230aecb3.png)

**Comment by Gk0Wk** [comment]
已添加nicolas的插件

**Comment by Gk0Wk** [comment]
好了
