### ISSUE TITLE
jd/Whitespace主题需要更新，版本变更0.0.18 到 0.0.23

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-CPL#57]
主题主页：http://j.d.whitespace.tiddlyspot.com/

该主题支持移动布局，移动布局的插件在安装介绍中。
![image](https://user-images.githubusercontent.com/32425955/179188433-f3f02bcf-31d8-44b6-b9da-ee75a2b2706c.png)

下载地址：
![image](https://user-images.githubusercontent.com/32425955/179187657-6f4c95dd-0e76-4766-87a4-df9b7c5ff95b.png)

**Comment by linonetwo** [comment]
它没有 github release 页面吗，如果有的话，基本是每小时自动更新的

**Comment by Zacharia2** [comment]
jd/mobvsimp的版本是一致的，不过jd/Whitespace的版本不是一致的，最新版是0.0.23。而CPL的是0.0.18
![image](https://user-images.githubusercontent.com/32425955/179857103-90a98eec-44af-43e3-bc03-8faa86f3d231.png)

**Comment by Gk0Wk** [comment]
好了
