### ISSUE TITLE
看板插件：ketan

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-CPL#59]
demo主页：https://ibnishak.github.io/Tesseract/projects/tekan/Tekan.html
![image](https://user-images.githubusercontent.com/32425955/179336955-bb175986-b4c9-4bbf-b9dd-7e3d912902b1.png)

效果展示：
![image](https://user-images.githubusercontent.com/32425955/179336936-eb52246f-ca49-4bff-84b0-4358778e0d8b.png)

**Comment by king0billy** [comment]
tekan插件检查更新bug：
1.tekan 插件： 新版没登录cpl导致会被旧版覆盖，明明我已安装新版
![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/52921954/87538cec-edfe-4dc0-91d0-1814a583089b)
![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/52921954/cd9aaa5d-3ac3-4e4f-a79e-0bbf48e410fa)


![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/52921954/5d3afa26-eaa0-4f5f-9fd2-374ea7a49f17)
![image](https://github.com/tiddly-gittly/TiddlyWiki-CPL/assets/52921954/1842e5ea-638c-4784-85b4-42c06203dda6)

**Comment by linonetwo** [comment]
@king0billy 可以PR更新它的 cpl.url 字段为新的网站
