### ISSUE TITLE
HTML Button 快速插入HTML

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-CPL#61]
https://keatonlao.github.io/tiddlywiki-xp/#%24%3A%2Fplugins%2Fxp%2Fhtml-button

![image](https://user-images.githubusercontent.com/32425955/179755426-1ed6d814-3823-4640-9753-a4ba00edb815.png)

**Comment by Gk0Wk** [comment]
已添加 XP 的全部插件。
