### ISSUE TITLE
tg/chars-button

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-CPL#63]
https://keatonlao.github.io/tiddlywiki-xp/#%24%3A%2Fplugins%2Ftg%2Fchars-button

![image](https://user-images.githubusercontent.com/32425955/179756983-bfc819ec-2060-4d89-bb5f-cc8ac02cb69c.png)

**Comment by Gk0Wk** [comment]
已添加 tg 插件。
