### ISSUE TITLE
关于按钮插件tg作者TonGerner

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-CPL#65]
讨论：https://github.com/Jermolene/TiddlyWiki5/issues/5379#issuecomment-757121996

http://tw5custom.tiddlyspot.com/
http://www.tongerner.nl/TW5/TW5_index.html
![image](https://user-images.githubusercontent.com/32425955/179759819-4c5b8d0d-ea74-4666-8caa-5169054701c6.png)

**Comment by Gk0Wk** [comment]
已添加 tg 插件。
